### ISSUE TITLE
Middleware not being called when on static files

### ISSUE THREAD

**Issue by ryanburnette** [richardschneider/express-mung#24]
@richardschneider Is it possible that [`mung.write`](<link rel="shortcut icon" type="image/png" href="http://example.com/favicon.png"/>) isn't called in some scenarios? My code looked something like this example below, but I wasn't getting the expected behavior. It was part of a larger project, but I'm working on a reduced complexity app to reproduce the issue.

```javascript
// kinda like...
var express = require('express')
var mung = require('express-mung')

var app = express()

app.use(express.static('public'))

app.use(mung.write(function (chunk,encoding,req,res) {
  console.log('hello world')
  return 'gotcha'
})
```

I would expect the body of the response to be `gotcha`, but it's not.

I would expect to see `hello world` in the console, but I don't.

**Comment by richardschneider** [comment]
@ryanburnette Thanks for spending your time to raise the issue.

As you found, `mung`  does not intercept `express.static` responses. This is because `express.static` does not  call [res.write](https://nodejs.org/api/http.html#http_response_write_chunk_encoding_callback) but pipes directly to the response stream.

I do not intend to fix this, because I see no reason to mung static content.

**Comment by ryanburnette** [comment]
Noted. At least this issue documents the limitation.

**Comment by richardschneider** [comment]
PS: I'm always happy to accept a Pull Request, if you really want this feature.
